package com.educo.tests.Helpers;import org.apache.commons.io.FileUtils;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.testng.Reporter;

import java.io.File;
import java.io.IOException;
import java.util.Date;

/**
 * Created with IntelliJ IDEA.
 * User: Mihai
 * Date: 7/10/13
 * Time: 3:27 PM
 * To change this template use File | Settings | File Templates.
 */
public class ScreenCapture {
    /**
     * The method creates an screenshot usually saved in output/screenshots
     * It also adds the screenshot to the index.html file generated by surefire-reports for ease of debugging
     * The method checks to see if the safari driver is used and if it is it will maximize the window so that it catches most of the page.
     *
     * @param LOG_FILE
     * //@param  the parameter is used to form the file usually is test_errorLocation_failed.png
     * @param driver
     */
    public static void screenShooter(String LOG_FILE,  WebDriver driver) {

        File dest = new File("test-output\\Screen.png");


            try {
                //((TakesScreenshot)driver).getScreenshotAs(target)

                System.setProperty("org.uncommons.reportng.escape-output", "false");
                File scrFile = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
                FileUtils.copyFile(scrFile, dest);
                String absolute = dest.getAbsolutePath();
                int beginIndex = absolute.indexOf(".");
                String relative = absolute.substring(beginIndex).replace(".\\","");
                String screenShot = relative.replace('\\','/');
                Reporter.log("<a href=\"" + screenShot + "\"><p align=\"left\">Screenshot at " + new Date()+ "</p>");
                Reporter.log("<p style='border:1px solid red;'><img width=\"800\" src=\"" + dest.getAbsoluteFile()  + "\" alt=\"screenshot at " + new Date()+ "\"/></p></a><br />");


            } catch (IOException e) {
                //Logger.Log(LOG_FILE, "Couldn't take the screenshot ",driver);
            }
    }



    }



